---
title: "Coronavirus (COVID-19)"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny 
source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shinyWidgets) # ##selection of country
library(countrycode)
library(sp)
library(DT)
library(shiny)
library(rvest)
library(xml2)
library(dplyr)
library(plotly)
library(leaflet)
library(leafpop)
library(purrr)
library(tibble)
library(rgdal)
library(highcharter)
#-------------------------------------------
source("cssfile/CSS.R", local = TRUE)

#------------------ Parameters ------------------
# Set colors
# https://www.w3.org/TR/css-color-3/#svg-color
confirmed_color <- "purple"
active_color <- "#1f77b4"
recovered_color <- "forestgreen"
death_color <- "red"
#set date for dashboardHHH
date <- Sys.Date() %>% format(., "%m/%d/%Y")
options(pkgdown.internet = FALSE)
#---------------------------------------------------- Data ------------------Data
# extract records from worldometers
 webpage_url <- "https://www.worldometers.info/coronavirus/"
 webpage <- xml2::read_html(webpage_url)
 ExOffndrsRaw <- rvest::html_table(webpage)[[1]] %>% 
   tibble::as_tibble(.name_repair = "unique") # repair the repeated columns
 cov_raw <- ExOffndrsRaw %>% 
   dplyr::glimpse(45)
 
 
 cov_raw <- cov_raw %>% 
   dplyr::rename(Country.Other= "Country,Other") %>%
   dplyr::rename(Serious.Critical= "Serious,Critical") 
 cov_raw<-cov_raw[,-c(10,11)]
##----------------------------------------------------------------------------End of Data
#cov_raw<-read.csv("C:/Users/DIEUDONNE/Desktop/Covid192/cov_raw.csv")

#cov_raw<-cov_raw[,-1]
#names(cov_raw)

cov_raw$Country.Other <-as.character(cov_raw$Country.Other)
cov_raw$TotalCases<-as.numeric(gsub(",", "", cov_raw$TotalCases))
cov_raw$NewCases<-as.numeric(gsub(",", "", cov_raw$NewCases))
cov_raw$TotalDeaths<-as.numeric(gsub(",", "",cov_raw$TotalDeaths))
cov_raw$NewDeaths <-as.numeric(gsub(",", "",  cov_raw$NewDeaths)) 
cov_raw$TotalRecovered<-as.numeric(gsub(",", "",cov_raw$TotalRecovered))
cov_raw$ActiveCases<-as.numeric(gsub(",", "",   cov_raw$ActiveCases ))  
cov_raw$Serious.Critical<-as.numeric(gsub(",", "", cov_raw$Serious.Critical))
#cov_raw$Tot.Cases.1M.pop<-as.numeric(gsub(",", "", cov_raw$Tot.Cases.1M.pop))

cov_raw <- subset(cov_raw, Country.Other!="Total:")
#cov_raw <- subset(cov_raw, Country.Other!=c("Diamond Princess", "MS Zaandam"))

d <- cov_raw %>% 
  dplyr::rename(Country.Region= "Country.Other") %>%
  dplyr::rename(Critical= "Serious.Critical") %>%
  dplyr::mutate(country = if_else(Country.Region == "CAR", "Central African Republic",
                 if_else(Country.Region == "Saint Martin", "St. Maarten",
                            if_else(Country.Region == "St. Barth", "Saint Barthelemy",
                               if_else(Country.Region == "Channel Islands", "Jersey", Country.Region)))))

#d <- d %>% 
#  dplyr::mutate(country = if_else(Country.Region == "Diamond Princess", "France", country))



d1 <- d %>% 
  dplyr::mutate(continent = countrycode(sourcevar = d[[10]],
                                 origin = "country.name",
                                 destination = "continent"))%>%
  dplyr::mutate(country = trimws(country)) 

d1$continent[is.na(d1$continent)] <- "Other"
# you can use  'destination = "region"' if you need region

d<-d1



# dplyr::mutate(country = dplyr::if_else(Country.Region == "United Arab Emirates", "UAE", Country.Region)) %>%
  # dplyr::mutate(country = dplyr::if_else(Country.Region == "Mainland China", "China", Country.Region)) %>%
  # dplyr::mutate(country = dplyr::if_else(Country.Region == "North Macedonia", "N.Macedonia", Country.Region))


```




Summary
=======================================================================
Column {.sidebar}
-----------------------------------------------------------------------

```{r, echo=FALSE}
inputPanel(
radioButtons("category",label= "Select continent",choices=c("All","Africa", "Americas",     "Asia",  "Europe" , "Oceania", "Other"),inline = F))


zone.choices2 = reactive({
  if(input$category=="All"){
    d
  }else{
  d %>%
  filter(continent==input$category)}
})

```

```{r, echo=FALSE}
MYdf<-reactive({
d <- zone.choices2() %>% 
  dplyr::filter(TotalCases > 0) %>% 
  dplyr::arrange(-TotalCases) %>%
  dplyr::mutate(country = trimws(country)) %>%
  dplyr::mutate(country = factor(country, levels = country))

})
```



```{r, echo=FALSE}

#selectInput("dataset","Choose :",choices = d$country)


renderUI({
inputPanel(
selectInput("Zone", label = "Country:",
          choices = c("All", levels(MYdf()$country)), selected = "All"))})

zone.choices = reactive({
  if (input$Zone=="All"){
  MYdf()
    }else{
  MYdf() %>%
  filter(country==input$Zone)}
})


```





For any question or feedback, you can either open an [issue](https://github.com/dniyitanga/covid19-africa-dashboard/issues) or contact me on [Twitter](https://twitter.com/dniyitanga) or [LinkedIn](https://www.linkedin.com/in/dieudonn%C3%A9-niyitanga-2212b585/).



Dieudonne NIYITANGA 

Philip Samuel MUTINDA


Data analysts at [BK](https://www.bk.rw/personal) 


Row
-----------------------------------------------------------------------

### Total confirmed ( ```r date```)

```{r}

renderValueBox({
dd<-as.data.frame(zone.choices())
valueBox(value = paste(format(sum(dd$TotalCases), big.mark = ","), "", sep = " "), 
         #caption = "Total Confirmed", 
         icon = "fas fa-user-md", 
         color = confirmed_color)
})
```

### Active cases ( ```r date```)

```{r}
renderValueBox({
dd<-as.data.frame(zone.choices())
valueBox(value = paste(format(sum(dd$ActiveCases, na.rm = TRUE), big.mark = ","), 
                       " (", round(100 * sum(dd$ActiveCases, na.rm = TRUE) / sum(dd$TotalCases), 1), 
                       "%)", sep = ""),  icon = "fas fa-ambulance", 
         color = active_color)
})
```

### Total recovered ( ```r date```)

```{r}
renderValueBox({
dd<-as.data.frame(zone.choices())
valueBox(value = paste(format(sum(dd$TotalRecovered, na.rm = TRUE), big.mark = ","), " (",
                       round(100 * sum(dd$TotalRecovered, na.rm = TRUE) / sum(dd$TotalCases), 1), 
                       "%)", sep = ""), 
          icon = "fas fa-heartbeat", 
         color = recovered_color)})

```

### Total Deaths ( ```r date```)

```{r}
renderValueBox({
dd<-as.data.frame(zone.choices())
valueBox(value = paste(format(sum(dd$TotalDeaths, na.rm = TRUE), big.mark = ","), " (",
                       round(100 * sum(dd$TotalDeaths, na.rm = TRUE) / sum(dd$TotalCases), 1), 
                       "%)", sep = ""),
          icon = "fas fa-heart-broken", 
         color = "black")})
```

### New Deaths (Only today)

```{r}
renderValueBox({
dd<-as.data.frame(zone.choices())
valueBox(value = paste(format(sum(dd$NewDeaths, na.rm = TRUE), big.mark = ",")),
          icon = "fas fa-heart-broken", 
         color = "black")})
```

###  New Cases (Only today)

```{r}
renderValueBox({
dd<-as.data.frame(zone.choices())
valueBox(value = paste(format(sum(dd$NewCases, na.rm = TRUE), big.mark = ",")),
          icon = "fas fa-heart-broken", 
         color = confirmed_color)})
```


Row 
-----------------------------------------------------------------------

### ACTIVE CASES ( ```r date```)

```{r}
renderUI({
d1<-as.data.frame(zone.choices())
Act<-format(sum(d1$ActiveCases, na.rm = TRUE), big.mark = ",")
mid<-sum(d1$ActiveCases, na.rm = TRUE)-sum(d1$Critical, na.rm = TRUE)
mid0<-paste( format(mid, big.mark = ","))
Cri<-paste(format(sum(d1$Critical, na.rm = TRUE), big.mark = ","))
rating <- round(100 * sum(d1$Critical, na.rm = TRUE) / sum(d1$ActiveCases), 1)
mid1 <- round(100 * mid/ sum(d1$ActiveCases), 1)
 fluidRow(column(12,paste("Currently Infected Patients  ",Sys.Date(),"are " ,Act," for with:")),
  column(6,"-In Mild Condition",gauge(mid1, min = 0, max = 100,symbol = '%',label=mid0, gaugeSectors( warning = c(0, 100)))),
  column(6,"-Serious or Critical",gauge(rating, min = 0, max = 100,symbol = '%',label=Cri, gaugeSectors(danger = c(0, 100)))))})
```


### CLOSED CASES ( ```r date```)

```{r}
renderUI({
d1<-as.data.frame(zone.choices())
Closed<-sum(d1$TotalRecovered, na.rm = TRUE)+sum(d1$TotalDeaths, na.rm = TRUE)
Recov <- round(100 * sum(d1$TotalRecovered, na.rm = TRUE) / Closed, 1)
Dead<- round(100 * sum(d1$TotalDeaths, na.rm = TRUE) / Closed, 1)
Dead1<-format(sum(d1$TotalDeaths, na.rm = TRUE),big.mark = ",")
Recov1 <- format(sum(d1$TotalRecovered, na.rm = TRUE), big.mark = ",")
Closed1<-format(Closed, big.mark = ",")
 fluidRow(column(12,paste("The  worldwide cases with Outcome ",Sys.Date()," are ",Closed1," with:")),
          br(),
             column(6,"-Recovered / Discharged", gauge(Recov, min = 0, max = 100,symbol = '%',label = Recov1, gaugeSectors(colors = recovered_color))),
             column(6,"-Deaths",gauge(Dead, min = 0, max = 100, symbol = '%',label = Dead1,gaugeSectors(
 colors = "black")))
           )
})
```


Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Cases Distribution by Type ( ```r date```)


```{r, echo=FALSE}
titleP<-reactive({
  if (input$category=="All"){
    paste0("Confirmed cases for all the countries in the World by ",Sys.Date(),".")
  }else if(input$Zone=="All"){
    paste0("Confirmed cases for all the countries in ",input$category," by ",Sys.Date(),".")
    }
  else{
      paste0("Confirmed cases in ",input$Zone," by ",Sys.Date(),".")

}
})
```


```{r }
MUDD41<-reactive({
  if(input$category=="All"){
    df<-d1%>%
    select("continent","TotalDeaths", "TotalRecovered", "ActiveCases")
  MUDD4<-as.data.frame(
    df %>%
      group_by(continent) %>% 
      summarise_each(funs(sum(., na.rm = TRUE)))%>%
      dplyr::rename(country= "continent"))
    }else{
  dd<-as.data.frame(zone.choices())
  MUDD4<-dd%>%
    select("country","TotalDeaths", "TotalRecovered", "ActiveCases")
    }
})
```



```{r df_summary}
renderHighchart({
categories_column <- names(MUDD41()[1])
measure_columns <- names(MUDD41()[,-1])

generated_chart <- highchart() %>%
  hc_xAxis(categories = MUDD41()[, categories_column],
           title = categories_column)

invisible(lapply(measure_columns, function(column) {
  generated_chart <<-
    hc_add_series(hc = generated_chart, name = column,
                  data = MUDD41()[, column])
}))

generated_chart <- generated_chart %>%
  hc_chart(type = "column") %>%
  hc_plotOptions(series = list(stacking = "normal",dataLabels = list(enabled = FALSE)))%>%
  hc_yAxis(title = list(text = "Coffirmed cases"),stackLabels = list(color = "black", enabled = TRUE))%>% 
  hc_exporting(enabled = TRUE)%>% 
  hc_title(text=titleP(),align="center")%>% 
  hc_tooltip(crosshairs = TRUE, backgroundColor = "#FCFFC5",
             shared = TRUE, borderWidth = 2)
  
  
})
```

Table
=======================================================================
Column {.sidebar}
-----------------------------------------------------------------------

```{r, echo=FALSE}
inputPanel(
radioButtons("category1",label= "Select continent",choices=c("Africa", "Americas",     "Asia",  "Europe" , "Oceania","Other")))

zone.choices3 = reactive({
    d1 %>%
  filter(continent==input$category1)
})

```

Row
-----------------------------------------------------------------------

### Recovery and Death Rates by Country ( ```r date```)

```{r, echo=FALSE}
DT::renderDataTable({

d <- zone.choices3()[,1:8] %>%
  dplyr::filter(TotalCases > 0) %>% 
  #dplyr::mutate_at(c(2,3,4,5,6,7,8,9), as.numeric) %>%
  dplyr::arrange(-TotalCases) 
  
})

```

